type THEMES = Record<string, any>;

export const COLORS = {
  primary: "#5142FC",
  primaryLight: "rgba(0,186,135,.15)",
  secondary: "#090A15",
  success: "#0ecb81",
  success_2: "#1EAF4E",
  success_3: "#03BF7A",
  sell: "#259242",
  success_4: "rgba(3, 191, 122, 0.30)",
  success_5: "#47a432",
  offer: "#CB1D2C",
  danger: "#ff4a5c",
  red: "#DF4949",
  info: "#627EEA",
  warning: "#E8A829",
  white: "#fff",
  dark: "#2f2f2f",
  light: "#E6E6E6",
  divider: "#7a798a81",
  placeholder: "#7A798A",
  yellow: "#E8A829",
  blue: "#05A9FC",
  neon: "#32F0FF",
  neon2: "#5EE2FE",
  transparent: "transparent",
  orange: "#FF5735",
  progress_bg: "#2B3062",
  dark_blue: "#4F6DC3",
  // light
  title: "#20212D",
  text: "#909090",
  background: "#e2e2e2",
  card: "#fff",
  border: "#7A798A",
  backgroundInput: "#1F222A",
  card2: "#ebebeb",
  notibar: "#fff",

  // dark
  darkTitle: "#fff",
  darkText: "#8A8AA0",
  darkBackground: "#181A20",
  darkCard: "#252731",
  darkBorder: "#252739",
  descriptionText: "#7A798A",
  greyBackground: "#1F222A",
  greySecondBg: "#181A20",
  borderColor: "#35383F",
  tabBarDark: "rgba(34, 36, 44, 0.85)",
  card2Dark: "#1a1c23",
  notibarDark: "#1F222A",

  // button
  buttonGrey: "#34383F",
  disabledBtn: "#343444",
  disbaledButton: "rgba(52, 52, 68, 0.5)",
};

export const IMAGES: THEMES = {
  bg1: "/images/background/bg1.png",
  bitcoin: "/images/coins/bitcoin.png",
  ethereum: "/images/coins/eth.png",
  logo160x160: "/images/images/COGI-ICO-Color.png",
  background: "/images/images/Background1.png",
  backgroundWallet: "/images/images/homepage/wallet.png",
  avatar: "/images/images/profile/avatar.png",
  success: "/images/images/homepage/success.png",
  processing: "/images/images/homepage/processing.png",
  error: "/images/images/component/perror.png",
  defaultAvatar: "/images/images/profile/default_avatar.png",
  metamask: "/images/metamask.png",
  wrong_network: "/images/img-network.png",
  staking: "/images/images/staking.png",
  land: "/images/images/Land/Land.png",
  mysteryBox: "/images/images/mysterybox/Box/GBOX.png",
  no_data: "/images/images_copy/staking/no_data.png",
  chart1_bg: "/images/images/dashboard/chart.png",
  chart1: "/images/images/dashboard/status-up.png",
  chart2_bg: "/images/images/dashboard/chart-volume.png",
  chart2: "/images/images/dashboard/chart-2.png",
  resource1: "/images/images/resource/icon_resource1.png",
  resource2: "/images/images/resource/icon_resource2.png",
  resource3: "/images/images/resource/icon_resource3.png",
  resource4: "/images/images/resource/icon_resource4.png",
  arrow_up: "/images/images/landing/Vector.png",
  earth: "/images/images/landing/img-world.png",
  common_bg: "/images/images/landing/Subtract.png",
  rare_bg: "/images/images/landing/Subtract_1.png",
  epic_bg: "/images/images/landing/Subtract_2.png",
  legend_bg: "/images/images/landing/Subtract_3.png",
  error_pc: "/images/images/component/error.png",
  nemo_big: "/images/images/icon-nemo.png",
};

export const STAR: THEMES = {
  hero_star: "/images/images/star/hero_star.png",
  hero_star_1: "/images/images/star/hero_star_1.png",
  hero_star_2: "/images/images/star/hero_star_2.png",
  hero_star_3: "/images/images/star/hero_star_3.png",
};

export const MAP: THEMES = {
  land_lv1: "/images/images/map/land_lv1.png",
  land_lv2: "/images/images/map/land_lv2.png",
  land_lv3: "/images/images/map/land_lv3.png",
  land_lv4: "/images/images/map/land_lv4.png",
  land_lv5: "/images/images/map/land_lv5.png",
  land_lv6: "/images/images/map/land_lv6.png",
  land_lv7: "/images/images/map/land_lv7.png",
  land_lv8: "/images/images/map/land_lv8.png",
  land_locked_1: "/images/images/map/land_locked_1.png",
  land_locked_2: "/images/images/map/land_locked_2.png",
  land_unlocked: "/images/images/map/land_unlocked.png",
  zone_unit: "/images/images/map/zone_unit.png",
};

export const QUALITY: THEMES = {
  White: "/images/images_copy/quality/1.png",
  Green: "/images/images_copy/quality/2.png",
  Blue: "/images/images_copy/quality/3.png",
  Violet: "/images/images_copy/quality/4.png",
  Yellow: "/images/images_copy/quality/5.png",
  Orange: "/images/images_copy/quality/6.png",
  Red: "/images/images_copy/quality/7.png",
  Platinum: "/images/images_copy/quality/8.png",
  null: "/images/images_copy/quality/null.png",
  White_big: "/images/images_copy/quality/1_big.png",
  Green_big: "/images/images_copy/quality/2_big.png",
  Blue_big: "/images/images_copy/quality/3_big.png",
  Violet_big: "/images/images_copy/quality/4_big.png",
  Yellow_big: "/images/images_copy/quality/5_big.png",
  Orange_big: "/images/images_copy/quality/6_big.png",
  Red_big: "/images/images_copy/quality/7_big.png",
  Platinum_big: "/images/images_copy/quality/8_big.png",
};

export const QUALITY_GALIX: THEMES = {
  "0-big": "/images/images_copy/quality/1_big.png",
  "1-big": "/images/images_copy/quality/2_big.png",
  "2-big": "/images/images_copy/quality/3_big.png",
  "3-big": "/images/images_copy/quality/4_big.png",
  "4-big": "/images/images_copy/quality/5_big.png",
  "5-big": "/images/images_copy/quality/6_big.png",
  "6-big": "/images/images_copy/quality/7_big.png",
  "7-big": "/images/images_copy/quality/8_big.png",
};

export const DASHBOARD_9D: THEMES = {
  White: "/images/images_copy/quality/dashboard/1.png",
  Green: "/images/images_copy/quality/dashboard/2.png",
  Blue: "/images/images_copy/quality/dashboard/3.png",
  Violet: "/images/images_copy/quality/dashboard/4.png",
  Yellow: "/images/images_copy/quality/dashboard/5.png",
  Gold: "/images/images_copy/quality/dashboard/5.png",
  Orange: "/images/images_copy/quality/dashboard/6.png",
  Red: "/images/images_copy/quality/dashboard/7.png",
  Platinum: "/images/images_copy/quality/dashboard/8.png",
  null: "/images/images_copy/quality/null.png",
};

export const TITLE_COLOR_QUALITY: THEMES = {
  Green: "#21A232",
  White: "#B6B6D2",
  Blue: "#0793FF",
  Violet: "#A15AFF",
  Purple: "#A15AFF",
  Gold: "#FFBF00",
  Yellow: "#FFBF00",
  Orange: "#FF5735",
  Red: "#FF1E1E",
  Platinum: "/images/images_copy/quality/8.png",
  "0-big": "#B6B6D2",
  "1-big": "#21A232",
  "2-big": "#0793FF",
  "3-big": "#A15AFF",
  "4-big": "#FFBF00",
  "5-big": "#FF5735",
  "6-big": "#FF1E1E",
};

export const SOCIALS: THEMES = {
  apple: "/images/images/SocialAP.png",
  facebook: "/images/images/SocialFB.png",
  google: "/images/images/SocialGG.png",
};

export const GAMES_AVATAR: THEMES = {
  bctest: "/images/games/bctest.png",
  "9dnft": "/images/games/9dnft.png",
  soulrealm: "/images/games/soulrealm.png",
  galixcity: "/images/games/galixcity.png",
  mechawarfare: "/images/games/mechawarfare.png",
  heavensword: "/images/games/heavensword.png",
  flashpoint: "/images/games/flashpoint.png",
  default: "/images/games/default.png",
};

export const ICONS: THEMES = {
  google: "/images/icons/google.png",
  chplay: "/images/icons/chplay.png",
  appstore: "/images/icons/appstore.png",
  homeWhite: "/images/icons/homeWhite.png",
  back: "/images/images/arrow-back.png",
  filter: "/images/icons/filter.png",
  share: "/images/icons/share.png",
  vietnam: "/images/images_copy/flag/VN.png",
  eng: "/images/images_copy/flag/eng.jpg",
  1: "/images/images/network/1.png",
  4: "/images/images/network/4.png",
  12: "/images/images/network/12.png",
  56: "/images/images/network/56.png",
  97: "/images/images/network/97.png",
  5555: "/images/images/network/5555.png",
  76923: "/images/images/network/76923.png",
  43113: "/images/images/network/43113.png",
  43114: "/images/images/network/43114.png",
  176923: "/images/images/network/176923.png",
  polygon_left: "/images/images/mysterybox/Polygon_3.png",
  polygon_right: "/images/images/mysterybox/Polygon_4.png",
  top_search: "/images/images/top_search.png",
  scan: "/images/icons/scan.png",
  nemo: "/icon-nemo.png",
};

const appTheme = { COLORS, IMAGES, ICONS };

export default appTheme;
