import { IAssetData } from "../common/types";
import { TYPE_DEPOSIT_WITHDRAW } from "../common/enum";

export const assets: IAssetData[] = [
  {
    contractNamespace: "eth_coin",
    contractBridge: "erc20_bridge",
    name: "zETH",
    symbol: "zETH",
    decimals: 18,
    icon: "/icon-zeth.png",
    icon_9d: "/images/images/mywallet/img_eth.png",
    native: true,
    allowSwap: false,
    // allowSwap: true,
    typeDeposit_Withdraw: [
      TYPE_DEPOSIT_WITHDRAW._TYPE_WITHDRAW,
      TYPE_DEPOSIT_WITHDRAW._TYPE_DEPOSIT,
    ],
  },
  // {
  //   contractNamespace: 'tst3_coin',
  //   contractBridge: 'erc20_bridge',
  //   name: 'TestToken3 Coin',
  //   symbol: 'TST3',
  //   decimals: 18,
  //   icon: image.icon_nemo,
  //   icon_9d: image.icon_nemo,
  //   native: false,
  //   allowSwap: false,
  //   // allowSwap: true,
  //   typeDeposit_Withdraw: [TYPE_DEPOSIT_WITHDRAW._TYPE_WITHDRAW],
  // },
  {
    contractNamespace: "nemo_coin",
    contractBridge: "erc20_bridge",
    name: "NEMO",
    symbol: "NEMO",
    decimals: 18,
    icon: "/icon-nemo.png",
    icon_9d: "/images/images/mywallet/img_nemo.png",
    native: false,
    allowSwap: false,
    typeDeposit_Withdraw: [
      TYPE_DEPOSIT_WITHDRAW._TYPE_WITHDRAW,
      TYPE_DEPOSIT_WITHDRAW._TYPE_DEPOSIT,
    ],
  },
  {
    contractNamespace: "usdc_coin",
    contractBridge: "erc20_bridge",
    name: "zUSDC",
    symbol: "zUSDC",
    decimals: 6,
    icon: "/icon-zusdc.png",
    icon_9d: "/images/images/mywallet/img_usdc.png",
    native: false,
    allowSwap: false,
    typeDeposit_Withdraw: [
      TYPE_DEPOSIT_WITHDRAW._TYPE_WITHDRAW,
      TYPE_DEPOSIT_WITHDRAW._TYPE_DEPOSIT,
    ],
  },
  {
    contractNamespace: "zion_coin",
    contractBridge: "erc20_bridge",
    name: "ZION",
    symbol: "ZION",
    icon: "/icon-zion.png",
    icon_9d: "/images/images/mywallet/img_nemo.png",
    decimals: 6,
    native: false,
    isErc404: false,
    allowSwap: true,
    typeDeposit_Withdraw: [
      TYPE_DEPOSIT_WITHDRAW._TYPE_WITHDRAW,
      TYPE_DEPOSIT_WITHDRAW._TYPE_DEPOSIT,
    ],
  },
  {
    contractNamespace: "wzion_coin",
    contractBridge: "erc20_bridge",
    name: "wZION",
    symbol: "wZION",
    icon: "/icon-zion.png",
    icon_9d: "/images/images/mywallet/img_nemo.png",
    decimals: 6,
    native: false,
    isErc404: true,
    allowSwap: true,
    typeDeposit_Withdraw: [
      TYPE_DEPOSIT_WITHDRAW._TYPE_WITHDRAW,
      TYPE_DEPOSIT_WITHDRAW._TYPE_DEPOSIT,
    ],
  },
];

export const assetsCoinNative: IAssetData = {
  contractNamespace: "eth_coin",
  contractBridge: "erc20_bridge",
  name: "zETH",
  symbol: "zETH",
  decimals: 18,
  icon: "/icon-zeth.png",
  icon_9d: "/images/images/mywallet/img_cogi.png",
  native: true,
  typeDeposit_Withdraw: [TYPE_DEPOSIT_WITHDRAW._TYPE_WITHDRAW, TYPE_DEPOSIT_WITHDRAW._TYPE_DEPOSIT],
};
